<?php

use App\Models\User;
use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\TestCase;

class AuthControllerTest extends TestCase
{
    use DatabaseMigrations;

    public function createApplication()
    {
        return require './bootstrap/app.php';
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    //O usuário não deve autenticar com o provedor errado.
    public function testUserShouldNotAuthenticateWithWrongProvider()
    {

        $payload = [
            'email' => 'deyziane.castelo@picpay.dev',
            'password' => 'deyziane12'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'deyziane']), $payload);

        $request->assertResponseStatus(422);
        $request->seeJson(['errors' => ['main' => 'Provider Not Found']]);
    }

    //O usuário deve ser negado se não estiver registrado
    public function testUserShouldBeDeniedIfNotRegistered()
    {

        $payload = [
            'email' => 'deyziane.castelo@picpay.dev',
            'password' => 'deyziane12'
        ];
        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(401);
        $request->seeJson(['errors' => ['main' => 'Wrong credentials']]);

    }
    //O usuário deve enviar a senha errada
    public function testUserShouldSendWrongPassword()
    {
        $user = User::factory()->create();

        $payload = [
            'email' => $user->email,
            'password' => 'deyziane'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(401);
        $request->seeJson(['errors' => ['main' => 'Wrong credentials']]);
    }

    //O usuário pode autenticar
    public function testUserCanAuthenticate()
    {
        $this->artisan('passport:install');
        $user = User::factory()->create();

        $payload = [
            'email' => $user->email,
            'password' => 'deyziane12'
        ];

        $request = $this->post(route('authenticate', ['provider' => 'user']), $payload);
        $request->assertResponseStatus(200);

        $request->dontSeeJson(['access_token','expires_at', 'provider']);
    }


}
